drop table if exists it_sprint_language cascade;

create table it_sprint_language
(
    id                  bigint generated by default as identity
        constraint itsprint_language_pkey
            primary key,
    compilation_command varchar(255),
    name                varchar(255),
    run_command         varchar(255),
    compiled_file_name  varchar(255),
    program_name        varchar(255)
);

alter table it_sprint_language
    owner to postgres;

INSERT INTO test.public.it_sprint_language (id, compilation_command, name, run_command, compiled_file_name, program_name) VALUES (1, 'g++ -static -std=c++14 -Wall,--stack=67108864 -O2 -o task.exe task.cpp', 'GNU G++ 14', 'task.exe', 'task.exe', 'task.cpp');
INSERT INTO test.public.it_sprint_language (id, compilation_command, name, run_command, compiled_file_name, program_name) VALUES (4, 'cl /TP /MT /EHsc /GL /O2 /W3 /F67108864 /Za /std:c++14 /D "_CRT_SECURE_NO_WARNINGS" /D "_CRT_SECURE_NO_DEPRECATE" task.cxx', 'Visual C++ 2017', 'task.exe', 'task.exe', 'task.cxx');
INSERT INTO test.public.it_sprint_language (id, compilation_command, name, run_command, compiled_file_name, program_name) VALUES (2, 'javac Main.java', 'Java 1.8', 'java -Xmx768m -Xss64m -Xms4m Main', 'Main.class', 'Main.java');
INSERT INTO test.public.it_sprint_language (id, compilation_command, name, run_command, compiled_file_name, program_name) VALUES (5, 'pabcnetclear task.pas', 'PascalABC.NET', 'task.exe', 'task.exe', 'task.pas');
INSERT INTO test.public.it_sprint_language (id, compilation_command, name, run_command, compiled_file_name, program_name) VALUES (3, null, 'Python 3.7', 'python task.py', 'task.py', 'task.py');
